"""SL-1 replay-equivalence + idempotence tests.

This is the crux of SL-1: prove that replaying a non-trivial committed event log
reproduces the canonical state, and that replay is deterministic.

Three committed artifacts under ``tests/fixtures/replay/sample-project/`` drive
these tests:

* ``events.jsonl``       — a realistic, deterministic audit log (project init,
                            multiple tasks, a claim with lease + heartbeat/renew,
                            a review acceptance, a stale-claim reap, a sync
                            mapping). Every line is a canonical event — no
                            tombstones (SL1-RR-1 guarantee).
* ``audit.jsonl``        — the sibling audit trail (rejections + idempotent
                            no-ops). Never replayed; present to prove the
                            scenario exercised both failure modes.
* ``expected-state.json`` — the golden ``serialize_state`` snapshot for that log.

Both artifacts are regenerated by a deliberate, documented human step — see
``tests/fixtures/replay/regenerate.py``. The tests NEVER regenerate them; a drift
between the committed golden and a freshly built/replayed snapshot is a real
failure to surface, not something to paper over.

Properties proven
------------------
1. **Equivalence** — building state the NORMAL way (append EventDrafts derived
   from the committed events) and the REPLAY way (replay_from_empty over the
   same events file) yields ``serialize_state`` outputs that are equal to each
   other AND equal to the committed golden snapshot.
2. **Idempotence** — replaying the same events into two independent scratch
   databases yields byte-identical snapshots.
3. **Poison-line impossibility** — the committed events.jsonl contains ZERO
   tombstone lines; every line is a real event that replay applies without a
   skip-list.

All scratch databases live under ``tmp_path`` and are never written into the
repo. No ``.db`` file is tracked.
"""

from __future__ import annotations

import json
import sqlite3
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest

from anvil.clock import FrozenClock
from anvil.state import models, payloads
from anvil.state.models import DEFAULT_PRD_ID, EventDraft
from anvil.state.snapshot import serialize_state
from anvil.state.sqlite import SqliteBackend

# Suite-wide frozen anchor (matches the generator and conftest).
_T0 = datetime(2026, 5, 24, 18, 0, 0, tzinfo=UTC)

_FIXTURE_DIR = Path(__file__).parent / "fixtures" / "replay" / "sample-project"
_EVENTS_PATH = _FIXTURE_DIR / "events.jsonl"
_AUDIT_PATH = _FIXTURE_DIR / "audit.jsonl"
_GOLDEN_PATH = _FIXTURE_DIR / "expected-state.json"


# ---------------------------------------------------------------------------
# Fixture loading helpers
# ---------------------------------------------------------------------------


def _load_committed_events() -> list[dict[str, Any]]:
    """Return the committed events.jsonl as a list of raw dicts."""
    with _EVENTS_PATH.open(encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]


def _load_golden() -> dict[str, Any]:
    """Return the committed golden snapshot dict."""
    with _GOLDEN_PATH.open(encoding="utf-8") as fh:
        return json.load(fh)


def _make_backend(state_dir: Path, *, db_name: str = "state.db") -> SqliteBackend:
    """A fresh, initialized SqliteBackend rooted under ``state_dir``.

    Uses a FrozenClock so any clock read during append/replay is deterministic.
    Both paths are fully deterministic.
    """
    db_path = str(state_dir / db_name)
    events_path = str(state_dir / "events.jsonl")
    Path(events_path).touch()
    b = SqliteBackend(db_path=db_path, events_path=events_path, clock=FrozenClock(_T0))
    b.initialize()
    return b


def _build_normal(state_dir: Path) -> SqliteBackend:
    """Build state the NORMAL way: append an EventDraft for each committed event.

    Each committed event is converted to an EventDraft (id stripped — the
    backend assigns sequential ids from its log-authority counter). Because the
    event sequence is identical, the backend assigns the same canonical ids
    E000001..E000024 and produces byte-equivalent state to replay_from_empty.

    This exercises the production write path (append) and proves it produces
    the same state as the replay path for the same event sequence.
    """
    b = _make_backend(state_dir)
    for raw in _load_committed_events():
        # Strip the id: EventDraft has no id field (the backend assigns it).
        draft_data = {k: v for k, v in raw.items() if k != "id"}
        draft = EventDraft.model_validate(draft_data)
        b.append(draft)
    return b


def _serialize(backend: SqliteBackend) -> dict[str, Any]:
    return serialize_state(backend)


def _canonical_json(snap: dict[str, Any]) -> str:
    return json.dumps(snap, sort_keys=True)


# ---------------------------------------------------------------------------
# Equivalence
# ---------------------------------------------------------------------------


def test_normal_and_replay_match_each_other_and_the_golden(tmp_path: Path) -> None:
    """serialize_state(normal) == serialize_state(replay) == committed golden.

    The 'normal' backend appends EventDrafts derived from the committed events;
    the 'replay' backend rebuilds via replay_from_empty over the same events
    file. All three snapshots must be byte-identical.
    """
    normal_dir = tmp_path / "normal"
    replay_dir = tmp_path / "replay"
    normal_dir.mkdir()
    replay_dir.mkdir()

    normal = _build_normal(normal_dir)
    replay = _make_backend(replay_dir)
    try:
        replay.replay_from_empty(str(_EVENTS_PATH))

        normal_snap = _serialize(normal)
        replay_snap = _serialize(replay)
        golden = _load_golden()

        # Vacuity guard: ensure the golden is non-degenerate before comparing.
        # If the golden were empty/blank, the three-way equality below would pass
        # vacuously even though replay is completely broken.
        assert golden["project"] is not None and len(golden["tasks"]) == 3, (
            "golden is degenerate (project is None or task count != 3) — "
            "regenerate the fixture via tests/fixtures/replay/regenerate.py"
        )

        normal_json = _canonical_json(normal_snap)
        replay_json = _canonical_json(replay_snap)
        golden_json = _canonical_json(golden)

        assert normal_json == replay_json, (
            "normal-path and replay-path snapshots diverge — replay does NOT "
            "reproduce canonical state. Diff the two serialize_state outputs to "
            "find the divergent collection."
        )
        assert replay_json == golden_json, (
            "replayed snapshot does not match the committed golden "
            "(expected-state.json). Either replay regressed, or the golden is "
            "stale — if the scenario legitimately changed, regenerate via "
            "tests/fixtures/replay/regenerate.py and commit the new artifacts."
        )
    finally:
        normal.close()
        replay.close()


def test_replayed_state_is_well_formed(tmp_path: Path) -> None:
    """Sanity: the replayed snapshot has the full canonical shape and content.

    Guards against a 'golden == replay' match that is vacuously true because
    both are empty/degenerate. Asserts the scenario's headline rows are present.
    """
    replay = _make_backend(tmp_path)
    try:
        replay.replay_from_empty(str(_EVENTS_PATH))
        snap = _serialize(replay)

        assert set(snap.keys()) == {
            "project", "prd", "features", "tasks",
            "claims", "reviews", "evidence", "requirements", "sync_mappings",
        }, (
            f"serialize_state returned unexpected keys {set(snap.keys())}. "
            "A likely cause is a new collection added to serialize_state — update "
            "the expected key set here AND regenerate the fixture."
        )
        assert snap["project"] is not None
        assert snap["prd"] is not None

        # Three tasks were created.
        assert {t["id"] for t in snap["tasks"]} == {"T001", "T002", "T003"}

        # Two claims, both terminal (released + stale) — proves list_claims (ALL).
        claims_by_id = {c["id"]: c["status"] for c in snap["claims"]}
        assert claims_by_id == {"C001": "released", "C002": "stale"}

        # Exactly one evidence row — the duplicate EV-DUP was a no-op (audit only).
        assert [e["id"] for e in snap["evidence"]] == ["EV001"]

        # The task.applied acceptance produced one review row.
        assert len(snap["reviews"]) == 1

        # The sync mapping survived replay.
        assert [(m["task_id"], m["external_system"]) for m in snap["sync_mappings"]] == [
            ("T001", "github_issues"),
        ]
    finally:
        replay.close()


def test_events_jsonl_contains_no_tombstone_lines() -> None:
    """The committed events.jsonl contains ZERO tombstone/audit lines.

    SL1-RR-1 guarantee: every line in events.jsonl is a real canonical event.
    Tombstones (rejections, idempotent no-ops) live in audit.jsonl only.
    replay_from_empty applies every line with no skip-list — poison lines are
    structurally impossible.
    """
    events = _load_committed_events()
    tombstone_actions = ("error.transaction_aborted", "warn.idempotent_no_op")
    for raw in events:
        action = raw.get("action", "")
        assert action not in tombstone_actions, (
            f"events.jsonl contains a tombstone line with action={action!r}. "
            "SL1-RR-1 requires all tombstones to live in audit.jsonl. "
            "Regenerate the fixture via tests/fixtures/replay/regenerate.py."
        )
    # Also verify all lines have the canonical E######-format id.
    for raw in events:
        eid = raw.get("id", "")
        assert eid.startswith("E") and eid[1:].isdigit(), (
            f"events.jsonl line has non-canonical id={eid!r}. "
            "Every line in events.jsonl must be a real event with a monotonic id."
        )


def test_audit_jsonl_contains_rejection_and_idempotent_no_op() -> None:
    """The committed audit.jsonl contains one rejection and one idempotent_no_op.

    These entries exist specifically to prove the scenario exercised both failure
    modes and that they landed in audit.jsonl, not events.jsonl.
    """
    with _AUDIT_PATH.open(encoding="utf-8") as fh:
        audit_lines = [json.loads(line) for line in fh if line.strip()]

    kinds = [entry.get("kind") for entry in audit_lines]
    assert "rejection" in kinds, (
        "audit.jsonl is missing a 'rejection' entry — the EventRejected path was "
        "not exercised. Regenerate the fixture."
    )
    assert "idempotent_no_op" in kinds, (
        "audit.jsonl is missing an 'idempotent_no_op' entry — the IdempotentNoOp "
        "path was not exercised. Regenerate the fixture."
    )
    # Audit entries must NOT have an 'id' field — they are not events.
    for entry in audit_lines:
        assert "id" not in entry, (
            f"audit.jsonl entry has an 'id' field: {entry!r}. "
            "Audit entries are not events and must not carry E###### ids."
        )


# ---------------------------------------------------------------------------
# Idempotence
# ---------------------------------------------------------------------------


def test_replay_is_idempotent_across_independent_dbs(tmp_path: Path) -> None:
    """Replaying the same events into two independent scratch dbs is byte-stable."""
    dir_a = tmp_path / "a"
    dir_b = tmp_path / "b"
    dir_a.mkdir()
    dir_b.mkdir()

    backend_a = _make_backend(dir_a)
    backend_b = _make_backend(dir_b)
    try:
        backend_a.replay_from_empty(str(_EVENTS_PATH))
        backend_b.replay_from_empty(str(_EVENTS_PATH))

        json_a = _canonical_json(_serialize(backend_a))
        json_b = _canonical_json(_serialize(backend_b))

        assert json_a == json_b, (
            "two independent replays of the same events produced different "
            "snapshots — replay is non-deterministic. This is a real replay bug."
        )
    finally:
        backend_a.close()
        backend_b.close()


def test_repeated_replay_into_same_backend_is_stable(tmp_path: Path) -> None:
    """Replaying twice into the SAME backend (delete+rebuild) is byte-stable.

    replay_from_empty deletes and recreates its own db on every call, so a
    second replay must reproduce the first replay's snapshot exactly.
    """
    backend = _make_backend(tmp_path)
    try:
        backend.replay_from_empty(str(_EVENTS_PATH))
        first = _canonical_json(_serialize(backend))

        backend.replay_from_empty(str(_EVENTS_PATH))
        second = _canonical_json(_serialize(backend))

        assert first == second
    finally:
        backend.close()


def test_no_tracked_db_artifacts_under_fixture_dir() -> None:
    """The committed fixture dir contains only the three text artifacts — no .db.

    Scratch databases must live under tmp_path; none may leak into the repo.
    The three expected artifacts are: events.jsonl, audit.jsonl,
    expected-state.json.
    """
    tracked = sorted(p.name for p in _FIXTURE_DIR.iterdir() if p.is_file())
    assert tracked == ["audit.jsonl", "events.jsonl", "expected-state.json"], (
        f"unexpected file(s) committed under the replay fixture dir: {tracked}. "
        "Scratch databases must live under tmp_path, never in the repo. "
        "Expected: audit.jsonl, events.jsonl, expected-state.json."
    )
    assert not any(p.suffix == ".db" for p in _FIXTURE_DIR.iterdir())


# ---------------------------------------------------------------------------
# T006 — SINGLE-PRD replay-equivalence oracle (SL-1)
#
# The 2-PRD byte-compare half is DEFERRED to Phase 6: serialize_state still
# emits a SINGLETON ``prd`` and does not enumerate multiple PRDs, so a
# byte-identical comparison of a directly-built 2-PRD backend against its
# replay is not yet expressible. This phase scopes the oracle to the
# single-PRD case (pre-v7 logs collapse to the 'default' partition) and leaves
# a clearly-marked xfail stub for the 2-PRD half (see test below).
#
# Because ``prd_id`` is ``Field(exclude=True)`` on the entity models, it does
# NOT appear in ``serialize_state`` output yet (Phase 2, T008-T010). These
# tests therefore assert the partition by querying the DB DIRECTLY.
# ---------------------------------------------------------------------------

# Entity tables whose ``prd_id`` column carries ``NOT NULL DEFAULT 'default'``
# in the v7 DDL, so a fresh-schema REPLAY (whose write-handlers do not yet
# persist prd_id — that is Phase 2 / T010) collapses every row into the default
# partition via the column DEFAULT.
_DEFAULT_BACKED_TABLES = ("tasks", "features", "requirements")

# All v7 prd-partitioned tables, including ``sync_mappings``. NOTE: under v7,
# ``sync_mappings.prd_id`` is NULLABLE with NO column DEFAULT — the v6->v7
# MIGRATION backfills it via a task-join UPDATE, but a REPLAY of a pre-v7 log
# leaves it NULL until the sync_mapping write-handler threads prd_id (Phase 2,
# T010 — explicitly out of scope here). The single-PRD oracle therefore asserts
# 'default' on the DEFAULT-backed tables and NULL-on-replay for sync_mappings.
_PRD_PARTITIONED_TABLES = (*_DEFAULT_BACKED_TABLES, "sync_mappings")


def _prd_id_or_none(db_path: str, table: str) -> list[str | None]:
    """Return DISTINCT ``prd_id`` values (including NULL) for ``table``, sorted
    with NULL first — read DIRECTLY, not via serialize_state."""
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        rows = conn.execute(
            f"SELECT DISTINCT prd_id FROM {table}"  # noqa: S608
        ).fetchall()
        return sorted((r[0] for r in rows), key=lambda v: (v is not None, v))
    finally:
        conn.close()


def _distinct_prd_ids(db_path: str, table: str) -> list[str]:
    """Return the DISTINCT ``prd_id`` values present in ``table``, sorted.

    Reads the SQLite db DIRECTLY (read-only) — NOT via serialize_state — because
    ``prd_id`` is ``Field(exclude=True)`` on the entity models and so is absent
    from the serialized snapshot in Phase 1.
    """
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        rows = conn.execute(
            f"SELECT DISTINCT prd_id FROM {table} ORDER BY prd_id"  # noqa: S608
        ).fetchall()
        return [r[0] for r in rows]
    finally:
        conn.close()


def _row_count(db_path: str, table: str) -> int:
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        return int(conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0])  # noqa: S608
    finally:
        conn.close()


def test_pre_v7_log_replays_every_row_into_default_prd(tmp_path: Path) -> None:
    """SINGLE-PRD oracle: a PRE-v7 events.jsonl (no prd_id keys) replayed from
    empty onto the v7 schema lands EVERY entity row under prd_id='default'.

    The committed fixture events.jsonl predates v7 — it carries zero ``prd_id``
    keys (asserted below as a guard) — so it is the canonical pre-v7 log for
    this oracle. After replay, every tasks/features/requirements/sync_mappings
    row must belong to the single default PRD partition. Asserted by querying
    the DB DIRECTLY, because ``prd_id`` is excluded from serialize_state.
    """
    # Guard: the fixture really is pre-v7 (no prd_id keys anywhere).
    raw_text = _EVENTS_PATH.read_text(encoding="utf-8")
    assert "prd_id" not in raw_text, (
        "the replay fixture events.jsonl now carries a 'prd_id' key — it is no "
        "longer a PRE-v7 log, so it cannot anchor the single-PRD oracle. Pick a "
        "different pre-v7 fixture or regenerate without prd_id keys."
    )

    replay = _make_backend(tmp_path)
    db_path = str(tmp_path / "state.db")
    try:
        replay.replay_from_empty(str(_EVENTS_PATH))

        # The v7 schema is stamped (replay re-creates the schema on open).
        assert replay.get_schema_version() == 7

        # The scenario produced real rows in every partitioned table (vacuity
        # guard — an all-empty DB would pass the 'every row is default' check
        # vacuously).
        assert _row_count(db_path, "tasks") == 3
        assert _row_count(db_path, "features") >= 1
        assert _row_count(db_path, "requirements") >= 1
        assert _row_count(db_path, "sync_mappings") >= 1

        # Every row in a DEFAULT-backed table belongs to the single default PRD
        # partition (the column DEFAULT does the backfill on a fresh-schema
        # replay).
        for table in _DEFAULT_BACKED_TABLES:
            assert _distinct_prd_ids(db_path, table) == [DEFAULT_PRD_ID], (
                f"{table} has rows outside the default PRD partition after "
                f"replaying a pre-v7 log: {_distinct_prd_ids(db_path, table)!r}"
            )

        # sync_mappings.prd_id is NULL on a pre-v7 REPLAY: its v7 column is
        # nullable with no DEFAULT, and the write-handler does not thread prd_id
        # until Phase 2 (T010). The v6->v7 MIGRATION backfills it to 'default'
        # via a task-join UPDATE — covered by TestV6ToV7Migration in
        # test_sqlite.py — but replay does not run that UPDATE. Asserting NULL
        # here pins the genuine Phase 1 state instead of papering over it.
        assert _prd_id_or_none(db_path, "sync_mappings") == [None], (
            "sync_mappings.prd_id changed on a pre-v7 replay — Phase 1 leaves it "
            "NULL (no column DEFAULT; write-handler prd_id is Phase 2/T010). If "
            "the write-handler now threads prd_id, move this to assert 'default' "
            "and update the Phase 1 scope note."
        )
    finally:
        replay.close()


def test_replay_matches_migrated_db_single_default_prd(tmp_path: Path) -> None:
    """The replay-reconstructed state matches the migrated-DB shape: a single
    default PRD owns every row, and row counts agree between two independent
    replays (the migrated-DB equivalent for a pre-v7 log is, by construction,
    the same single-default partition).

    Row counts are the cross-check the packet asks for: the default PRD owns
    every row and no row is lost or duplicated relative to a second replay.
    """
    dir_a = tmp_path / "a"
    dir_b = tmp_path / "b"
    dir_a.mkdir()
    dir_b.mkdir()

    backend_a = _make_backend(dir_a)
    backend_b = _make_backend(dir_b)
    db_a = str(dir_a / "state.db")
    db_b = str(dir_b / "state.db")
    try:
        backend_a.replay_from_empty(str(_EVENTS_PATH))
        backend_b.replay_from_empty(str(_EVENTS_PATH))

        for table in _PRD_PARTITIONED_TABLES:
            # Same row count across the two independent replays …
            assert _row_count(db_a, table) == _row_count(db_b, table), table

        # … and every row in a DEFAULT-backed table belongs to the default PRD.
        for table in _DEFAULT_BACKED_TABLES:
            assert _distinct_prd_ids(db_a, table) == [DEFAULT_PRD_ID], table
            assert _distinct_prd_ids(db_b, table) == [DEFAULT_PRD_ID], table

        # sync_mappings.prd_id is NULL on replay in Phase 1 (see the single-PRD
        # oracle above) — assert it stays consistent across both replays rather
        # than asserting 'default' the replay write-path does not yet produce.
        assert (
            _prd_id_or_none(db_a, "sync_mappings")
            == _prd_id_or_none(db_b, "sync_mappings")
            == [None]
        )

        # The prds table holds exactly one row, the default PRD (id='default').
        #
        # On a pre-v7 REPLAY the prd.parsed write-handler now creates the row
        # with is_default=1 (BUG 001 fix — the UPSERT INSERT path stamps the v7
        # identity columns), matching what the v6->v7 MIGRATION mints. So both
        # the replay and migration paths converge on the same single-default
        # partition: exactly one prds row, id='default', is_default=1.
        conn = sqlite3.connect(f"file:{db_a}?mode=ro", uri=True)
        try:
            prds = conn.execute("SELECT id, is_default FROM prds").fetchall()
        finally:
            conn.close()
        assert prds == [(DEFAULT_PRD_ID, 1)]
    finally:
        backend_a.close()
        backend_b.close()


def test_replay_from_empty_on_v7_reconstructs_same_task_statuses_and_claims(
    tmp_path: Path,
) -> None:
    """T014 (criterion 3) — ``replay_from_empty`` over the ORIGINAL (pre-v7)
    events.jsonl on a v7 schema reconstructs the SAME task statuses and claims.

    The committed fixture events.jsonl is a genuine pre-v7 log (no ``prd_id``
    keys — guarded below). Replaying it onto a freshly created v7 backend must
    reproduce the canonical task-status and claim-status set captured in the
    golden snapshot: the v6->v7 schema change carries zero new fields into the
    status/claim projections, so the replay verdict is invariant across the
    schema bump. This is the replay half of the v6->v7 gate-equivalence proof
    (the migration half lives in TestV6ToV7Migration in test_sqlite.py).
    """
    # Guard: the log really is pre-v7 (no prd_id keys), so this exercises the
    # "original events.jsonl on v7" path the criterion names.
    raw_text = _EVENTS_PATH.read_text(encoding="utf-8")
    assert "prd_id" not in raw_text, (
        "the replay fixture events.jsonl now carries a 'prd_id' key — it is no "
        "longer the ORIGINAL pre-v7 log this gate-equivalence test needs."
    )

    replay = _make_backend(tmp_path)
    try:
        replay.replay_from_empty(str(_EVENTS_PATH))

        # The replay re-created the schema at v7 (the engine's current version).
        assert replay.get_schema_version() == 7

        golden = _load_golden()
        # Vacuity guard: the golden encodes a non-degenerate status/claim set.
        assert len(golden["tasks"]) == 3 and len(golden["claims"]) == 2, (
            "golden is degenerate — regenerate via "
            "tests/fixtures/replay/regenerate.py"
        )

        # Task statuses reconstructed by the v7 replay == the golden statuses.
        replayed_task_status = {t.id: t.status.value for t in replay.list_tasks()}
        golden_task_status = {t["id"]: t["status"] for t in golden["tasks"]}
        assert replayed_task_status == golden_task_status

        # Claim statuses reconstructed by the v7 replay == the golden claims.
        replayed_claim_status = {c.id: c.status.value for c in replay.list_claims()}
        golden_claim_status = {c["id"]: c["status"] for c in golden["claims"]}
        assert replayed_claim_status == golden_claim_status
    finally:
        replay.close()


def test_default_prd_id_is_single_source_for_migration_and_payloads() -> None:
    """DEFAULT_PRD_ID is THE single source of the 'default' partition literal.

    A pre-v7 log replays into the same partition the v6->v7 migration mints, so
    the migration backfill literal and the payload-default literal MUST both be
    ``DEFAULT_PRD_ID``. We assert:

    * the constant value is exactly 'default';
    * the migration backfill literal (in _m_to_v7's source) equals the constant;
    * the payload prd_id defaults all resolve to the constant.

    If these ever diverge, a pre-v7 replay would fork from the migrated DB.
    """
    # 1. The constant value.
    assert models.DEFAULT_PRD_ID == "default"
    assert DEFAULT_PRD_ID == "default"

    # 2. The migration backfill literal equals the constant. The v6->v7 ALTERs
    #    backfill via ``DEFAULT '<literal>'`` in raw SQL; that literal must be
    #    DEFAULT_PRD_ID or a pre-v7 log forks from the migrated DB. We assert the
    #    literal text the migration emits matches the constant.
    import inspect

    from anvil.state import sqlite as sqlite_mod

    # The migration body lives in _m_to_v7_body (wrapped atomically by
    # _m_to_v7 — BUG 002 fix); inspect both so the literal check sees the
    # actual ALTER/INSERT SQL, not just the wrapper.
    migration_src = inspect.getsource(
        sqlite_mod.SqliteBackend._m_to_v7
    ) + inspect.getsource(sqlite_mod.SqliteBackend._m_to_v7_body)
    assert f"DEFAULT '{DEFAULT_PRD_ID}'" in migration_src, (
        "the v6->v7 migration no longer backfills prd_id with the "
        f"DEFAULT_PRD_ID literal {DEFAULT_PRD_ID!r}. The migration backfill and "
        "DEFAULT_PRD_ID must stay the SINGLE source, or pre-v7 replay forks "
        "from the migrated DB."
    )
    # And the prds default row id literal.
    assert f"'{DEFAULT_PRD_ID}'" in migration_src

    # 3. The payload prd_id defaults resolve to the same constant. Each pre-v7
    #    payload that scopes an entity defaults prd_id to DEFAULT_PRD_ID so a log
    #    with no prd_id key collapses into the default partition.
    for payload_cls in (
        payloads.PrdParsedPayload,
        payloads.FeatureCreatedPayload,
        payloads.TaskCreatedPayload,
    ):
        default = payload_cls.model_fields["prd_id"].default
        assert default == DEFAULT_PRD_ID, (
            f"{payload_cls.__name__}.prd_id defaults to {default!r}, not the "
            f"DEFAULT_PRD_ID constant {DEFAULT_PRD_ID!r}."
        )


@pytest.mark.xfail(
    reason=(
        "2-PRD byte-compare oracle is DEFERRED to Phase 6: serialize_state "
        "still emits a SINGLETON 'prd' and does not enumerate multiple PRDs, so "
        "json.dumps(serialize_state(b), sort_keys=True) cannot yet be "
        "byte-identical between a directly-built 2-PRD backend and its "
        "replay_from_empty. Implement once serialize_state enumerates a sorted "
        "'prds' collection (Phase 6); do NOT change serialize_state here."
    ),
    strict=True,
    run=False,
)
def test_two_prd_replay_byte_equivalence_phase6() -> None:  # pragma: no cover
    """TODO(Phase 6): directly-build a 2-PRD backend, replay_from_empty over the
    same events, and assert json.dumps(serialize_state(b), sort_keys=True) is
    byte-identical between the two. Blocked on serialize_state multi-PRD
    enumeration (the singleton 'prd' key must become a sorted 'prds' list).
    """
    raise NotImplementedError("Phase 6: serialize_state multi-PRD enumeration")
